/* Sample doc for the "Try the sample" button. A made-up studio on example.com, written the way a strategist
   might: a campaign table, headings per ad set, bullet lists, an ad table and a few lines the tool should not import. */
(function (root) {
  'use strict';
  const SAMPLE_TEXT = [
    '# Juniper Pilates – Meta Ads Plan',
    '',
    'Website: https://www.example.com/',
    'UTM parameters: utm_source=meta&utm_medium=paid_social',
    '',
    '## Campaign summary',
    '| Campaign | Objective | Monthly Budget | Ad Sets |',
    '|---|---|---|---|',
    '| Intro Offer | Sales | $1,216 | Local Fitness Interest; Lookalike 1% Members |',
    '| Retargeting | Leads (Instant Form) | $304 | Site Visitors 30 Days |',
    '',
    '## Campaign 1: Intro Offer',
    'Conversion event: Purchase',
    '',
    '### Local Fitness Interest',
    '- Location: Austin, TX + 15 mile radius',
    '- Age: 25-45',
    '- Gender: Women',
    '- Interests: Pilates, Yoga, Barre, Lululemon',
    '- Exclude: Current members (customer list)',
    '- Placements: Instagram Feed, Stories and Reels; Facebook Feed',
    '',
    '**Ad 1 – Studio tour reel**',
    '**Primary Text:**',
    'New to reformer Pilates? Your first month starts here.',
    '✨ Unlimited classes for 30 days',
    '✨ Small groups, real coaching',
    '**Headline:** 30 Days of Pilates for $49',
    '**Description:** New students only',
    '**CTA:** Shop Now',
    '**Format:** 15s Reel video',
    '',
    '**Ad 2 – Class photo**',
    '**Primary Text:** Strong core, better posture, zero guesswork. Try a month of classes for $49.',
    '**Headline:** Your Intro Month Is Waiting',
    '**CTA:** Learn More',
    '',
    '### Lookalike 1% Members',
    '- Audience: 1% lookalike of current members',
    '- Location: Austin, TX',
    '- Age: 21-55',
    '',
    '**Primary Text Options:**',
    '1. Austin\'s friendliest Pilates studio has a deal for new students.',
    '2. Stressed? Stretch it out. 30 days unlimited for $49.',
    '',
    '**Headlines:**',
    '- $49 for 30 Days Unlimited',
    '- Your First Class Is Free',
    '',
    '## Campaign 2: Retargeting',
    '',
    '### Site Visitors 30 Days',
    '- Custom audience: Website visitors (30 days)',
    '- Exclude: Purchasers (30 days)',
    '- Location: Austin, TX',
    '',
    '| Ad | Primary Text | Headline | CTA |',
    '|---|---|---|---|',
    '| Reminder | Still thinking about it? Your intro month is waiting. | Claim Your Intro Month | Sign Up |',
    '| Reviews | 4.9 stars from 300+ Austin members. Come see why. | Loved by Austin | Sign Up |',
    '',
    '## Testing plan',
    '- Move budget to the best ad set after 14 days.',
    '- Test UGC video against the studio tour once we have 50 purchases.'
  ].join('\n');
  root.MBSample = { name: 'Juniper_Pilates_sample.md', text: SAMPLE_TEXT };
})(typeof window !== 'undefined' ? window : globalThis);
